services:
  web_server:
    build: ./backend-nest
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
    container_name: backend-nest
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./backend-nest:/web
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - TZ=Europe/Berlin
    restart: always
  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name: maria-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
