name: pub_diferent
description: "ApplicaciÃ³n para el Pub Diferent"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.2.4
  http: ^1.5.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  riverpod: ^3.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
